# Form implementation generated from reading ui file 'loading-screen.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(403, 70)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dialog_text = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(10)
        self.dialog_text.setFont(font)
        self.dialog_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dialog_text.setObjectName("dialog_text")
        self.verticalLayout.addWidget(self.dialog_text)
        self.loading_progress_bar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.loading_progress_bar.setProperty("value", 0)
        self.loading_progress_bar.setTextVisible(False)
        self.loading_progress_bar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.loading_progress_bar.setTextDirection(QtWidgets.QProgressBar.Direction.TopToBottom)
        self.loading_progress_bar.setObjectName("loading_progress_bar")
        self.verticalLayout.addWidget(self.loading_progress_bar)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dialog_text.setText(_translate("MainWindow", "Loading elements..."))
