# Form implementation generated from reading ui file 'login-page.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        # Main Window
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(400, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 400))
        MainWindow.setMaximumSize(QtCore.QSize(400, 400))
        MainWindow.setStatusTip("")
        MainWindow.setStyleSheet("background-color: rgb(211, 211, 211)")

        # Central Widget and Layout
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        # Title Section
        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setMaximumSize(QtCore.QSize(16777215, 125))
        font = QtGui.QFont()
        font.setFamily("Oswald SemiBold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.gridLayout.addWidget(self.title_label, 0, 0, 1, 1)

        # Username Section
        self.username_container = QtWidgets.QWidget(parent=self.centralwidget)
        self.username_container.setMaximumSize(QtCore.QSize(500, 50))
        self.username_container.setObjectName("username_container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.username_container)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.username_label = QtWidgets.QLabel(parent=self.username_container)
        self.username_label.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Oswald Medium")
        font.setPointSize(14)
        self.username_label.setFont(font)
        self.username_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.username_label.setObjectName("username_label")
        self.horizontalLayout.addWidget(self.username_label)
        self.username_lineedit = QtWidgets.QLineEdit(parent=self.username_container)
        self.username_lineedit.setMaximumSize(QtCore.QSize(210, 25))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(10)
        self.username_lineedit.setFont(font)
        self.username_lineedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.username_lineedit.setText("")
        self.username_lineedit.setObjectName("username_lineedit")
        self.horizontalLayout.addWidget(self.username_lineedit)
        self.gridLayout.addWidget(self.username_container, 3, 0, 1, 1)

        # Password Section
        self.password_container = QtWidgets.QWidget(parent=self.centralwidget)
        self.password_container.setMaximumSize(QtCore.QSize(500, 50))
        self.password_container.setObjectName("password_container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.password_container)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.password_label = QtWidgets.QLabel(parent=self.password_container)
        self.password_label.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Oswald Medium")
        font.setPointSize(14)
        self.password_label.setFont(font)
        self.password_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.password_label.setObjectName("password_label")
        self.horizontalLayout_2.addWidget(self.password_label)
        self.password_lineedit = QtWidgets.QLineEdit(parent=self.password_container)
        self.password_lineedit.setMaximumSize(QtCore.QSize(210, 25))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(10)
        self.password_lineedit.setFont(font)
        self.password_lineedit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.password_lineedit.setText("")
        self.password_lineedit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_lineedit.setObjectName("password_lineedit")
        self.horizontalLayout_2.addWidget(self.password_lineedit)
        self.gridLayout.addWidget(self.password_container, 4, 0, 1, 1)

        # Show Password Section
        self.show_password_container = QtWidgets.QWidget(parent=self.centralwidget)
        self.show_password_container.setMaximumSize(QtCore.QSize(500, 25))
        self.show_password_container.setObjectName("show_password_container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.show_password_container)
        self.verticalLayout.setContentsMargins(40, 0, -1, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.show_password_checkbox = QtWidgets.QCheckBox(parent=self.show_password_container)
        self.show_password_checkbox.setEnabled(True)
        self.show_password_checkbox.setMinimumSize(QtCore.QSize(20, 25))
        self.show_password_checkbox.setMaximumSize(QtCore.QSize(125, 25))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(10)
        self.show_password_checkbox.setFont(font)
        self.show_password_checkbox.setCheckable(True)
        self.show_password_checkbox.setChecked(False)
        self.show_password_checkbox.setTristate(False)
        self.show_password_checkbox.setObjectName("show_password_checkbox")
        self.verticalLayout.addWidget(self.show_password_checkbox)
        self.gridLayout.addWidget(self.show_password_container, 5, 0, 1, 1)

        # Buttons Section
        self.buttons_container = QtWidgets.QWidget(parent=self.centralwidget)
        self.buttons_container.setMaximumSize(QtCore.QSize(16777215, 100))
        self.buttons_container.setObjectName("buttons_container")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.buttons_container)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sign_up_button = QtWidgets.QPushButton(parent=self.buttons_container)
        self.sign_up_button.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Oswald Medium")
        font.setPointSize(11)
        self.sign_up_button.setFont(font)
        self.sign_up_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(179, 179, 179);\n"
"border-radius: 2px;\n"
"border-width: 1px;\n"
"border-color: black;\n"
"border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(165, 165, 165);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(145, 145, 145);\n"
"}\n"
"\n"
"")
        self.sign_up_button.setObjectName("sign_up_button")
        self.horizontalLayout_3.addWidget(self.sign_up_button)
        self.login_button = QtWidgets.QPushButton(parent=self.buttons_container)
        self.login_button.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Oswald Medium")
        font.setPointSize(11)
        self.login_button.setFont(font)
        self.login_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(179, 179, 179);\n"
"border-radius: 2px;\n"
"border-width: 1px;\n"
"border-color: black;\n"
"border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(165, 165, 165);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(145, 145, 145);\n"
"}\n"
"\n"
"")
        self.login_button.setObjectName("login_button")
        self.horizontalLayout_3.addWidget(self.login_button)
        self.gridLayout.addWidget(self.buttons_container, 6, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Movie and TV Show Review App"))
        self.title_label.setText(_translate("MainWindow", "Movie and TV Show Review App"))
        self.username_label.setText(_translate("MainWindow", "Username"))
        self.sign_up_button.setText(_translate("MainWindow", "Sign Up"))
        self.login_button.setText(_translate("MainWindow", "Log In"))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.show_password_checkbox.setText(_translate("MainWindow", "Show password?"))
