# Form implementation generated from reading ui file 'signup-dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        # Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 252)
        Dialog.setStyleSheet("background-color: rgb(211, 211, 211)")

        # Layout
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")

        # Username Section
        self.username_container = QtWidgets.QWidget(parent=Dialog)
        self.username_container.setMaximumSize(QtCore.QSize(500, 50))
        self.username_container.setObjectName("username_container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.username_container)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.username_label = QtWidgets.QLabel(parent=self.username_container)
        self.username_label.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Oswald Medium")
        font.setPointSize(14)
        self.username_label.setFont(font)
        self.username_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.username_label.setObjectName("username_label")
        self.horizontalLayout.addWidget(self.username_label)
        self.username_lineedit = QtWidgets.QLineEdit(parent=self.username_container)
        self.username_lineedit.setMaximumSize(QtCore.QSize(210, 25))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(10)
        self.username_lineedit.setFont(font)
        self.username_lineedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.username_lineedit.setText("")
        self.username_lineedit.setObjectName("username_lineedit")
        self.horizontalLayout.addWidget(self.username_lineedit)
        self.gridLayout.addWidget(self.username_container, 0, 0, 1, 1)

        # Password Section
        self.password_container = QtWidgets.QWidget(parent=Dialog)
        self.password_container.setMaximumSize(QtCore.QSize(500, 50))
        self.password_container.setObjectName("password_container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.password_container)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.password_label = QtWidgets.QLabel(parent=self.password_container)
        self.password_label.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Oswald Medium")
        font.setPointSize(14)
        self.password_label.setFont(font)
        self.password_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.password_label.setObjectName("password_label")
        self.horizontalLayout_2.addWidget(self.password_label)
        self.password_lineedit = QtWidgets.QLineEdit(parent=self.password_container)
        self.password_lineedit.setMaximumSize(QtCore.QSize(210, 25))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(10)
        self.password_lineedit.setFont(font)
        self.password_lineedit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.password_lineedit.setText("")
        self.password_lineedit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_lineedit.setObjectName("password_lineedit")
        self.horizontalLayout_2.addWidget(self.password_lineedit)
        self.gridLayout.addWidget(self.password_container, 1, 0, 1, 1)

        # Confirm Password Section
        self.confirm_password_container = QtWidgets.QWidget(parent=Dialog)
        self.confirm_password_container.setMaximumSize(QtCore.QSize(500, 50))
        self.confirm_password_container.setObjectName("confirm_password_container")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.confirm_password_container)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.confirm_password_label = QtWidgets.QLabel(parent=self.confirm_password_container)
        self.confirm_password_label.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Oswald Medium")
        font.setPointSize(14)
        self.confirm_password_label.setFont(font)
        self.confirm_password_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.confirm_password_label.setObjectName("confirm_password_label")
        self.horizontalLayout_3.addWidget(self.confirm_password_label)
        self.confirm_password_lineedit = QtWidgets.QLineEdit(parent=self.confirm_password_container)
        self.confirm_password_lineedit.setMaximumSize(QtCore.QSize(210, 25))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(10)
        self.confirm_password_lineedit.setFont(font)
        self.confirm_password_lineedit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.confirm_password_lineedit.setText("")
        self.confirm_password_lineedit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.confirm_password_lineedit.setObjectName("confirm_password_lineedit")
        self.horizontalLayout_3.addWidget(self.confirm_password_lineedit)
        self.gridLayout.addWidget(self.confirm_password_container, 3, 0, 1, 1)

        # Sign Up Button Section
        self.sign_up_button_container = QtWidgets.QWidget(parent=Dialog)
        self.sign_up_button_container.setObjectName("sign_up_button_container")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.sign_up_button_container)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sign_up_button = QtWidgets.QPushButton(parent=self.sign_up_button_container)
        self.sign_up_button.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Oswald Medium")
        font.setPointSize(11)
        self.sign_up_button.setFont(font)
        self.sign_up_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(179, 179, 179);\n"
"border-radius: 2px;\n"
"border-width: 1px;\n"
"border-color: black;\n"
"border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(165, 165, 165);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(145, 145, 145);\n"
"}\n"
"\n"
"")
        self.sign_up_button.setObjectName("sign_up_button")
        self.horizontalLayout_4.addWidget(self.sign_up_button)
        self.gridLayout.addWidget(self.sign_up_button_container, 6, 0, 1, 1)


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Create An Account"))
        self.sign_up_button.setText(_translate("Dialog", "Sign Up"))
        self.confirm_password_label.setText(_translate("Dialog", "Confirm Password"))
        self.username_label.setText(_translate("Dialog", "Username"))
        self.password_label.setText(_translate("Dialog", "Password"))
