# Form implementation generated from reading ui file 'application-window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(924, 749)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.choose_titles_page = QtWidgets.QWidget()
        self.choose_titles_page.setObjectName("choose_titles_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.choose_titles_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.popular_movies_scroll_area = QtWidgets.QScrollArea(parent=self.choose_titles_page)
        self.popular_movies_scroll_area.setMinimumSize(QtCore.QSize(0, 260))
        self.popular_movies_scroll_area.setMaximumSize(QtCore.QSize(16777215, 300))
        self.popular_movies_scroll_area.setStyleSheet("\n"
"QScrollBar:horizontal{\n"
"    border: none;\n"
"    background-color: rgb(43, 56, 138);\n"
"    height: 10px;\n"
"    margin: 0 0 0 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal{\n"
"    background-color: rgb(131, 207, 241);\n"
"    min-width: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal:hover{\n"
"    background-color: rgb(131, 180, 210);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:pressed{\n"
"    background-color: rgb(120, 170, 190);\n"
"}\n"
"\n"
"\n"
"")
        self.popular_movies_scroll_area.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.popular_movies_scroll_area.setLineWidth(1)
        self.popular_movies_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.popular_movies_scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.popular_movies_scroll_area.setWidgetResizable(True)
        self.popular_movies_scroll_area.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.popular_movies_scroll_area.setObjectName("popular_movies_scroll_area")
        self.popular_movies_scroll_area_contents = QtWidgets.QWidget()
        self.popular_movies_scroll_area_contents.setGeometry(QtCore.QRect(0, 0, 830, 250))
        self.popular_movies_scroll_area_contents.setObjectName("popular_movies_scroll_area_contents")
        self.gridLayout = QtWidgets.QGridLayout(self.popular_movies_scroll_area_contents)
        self.gridLayout.setContentsMargins(-1, 9, -1, 9)
        self.gridLayout.setObjectName("gridLayout")
        self.temp_movie_poster = QtWidgets.QLabel(parent=self.popular_movies_scroll_area_contents)
        self.temp_movie_poster.setMinimumSize(QtCore.QSize(165, 225))
        self.temp_movie_poster.setMaximumSize(QtCore.QSize(165, 270))
        self.temp_movie_poster.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.temp_movie_poster.setStyleSheet("QLabel{\n"
"background-color: orange;\n"
"border-style: outset;\n"
"}\n"
"\n"
"QLabel:hover{\n"
"border: 4px solid blue;\n"
"border-radius: 1px;\n"
"}\n"
"\n"
"")
        self.temp_movie_poster.setText("")
        self.temp_movie_poster.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.temp_movie_poster.setObjectName("temp_movie_poster")
        self.gridLayout.addWidget(self.temp_movie_poster, 0, 0, 1, 1)
        self.popular_movies_scroll_area.setWidget(self.popular_movies_scroll_area_contents)
        self.gridLayout_4.addWidget(self.popular_movies_scroll_area, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.gridLayout_4.addItem(spacerItem, 7, 1, 1, 1)
        self.popular_tv_shows_scroll_area = QtWidgets.QScrollArea(parent=self.choose_titles_page)
        self.popular_tv_shows_scroll_area.setMinimumSize(QtCore.QSize(0, 260))
        self.popular_tv_shows_scroll_area.setMaximumSize(QtCore.QSize(16777215, 300))
        self.popular_tv_shows_scroll_area.setStyleSheet("\n"
"QScrollBar:horizontal{\n"
"    border: none;\n"
"    background-color: rgb(43, 56, 138);\n"
"    height: 10px;\n"
"    margin: 0 0 0 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal{\n"
"    background-color: rgb(131, 207, 241);\n"
"    min-width: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal:hover{\n"
"    background-color: rgb(131, 180, 210);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:pressed{\n"
"    background-color: rgb(120, 170, 190);\n"
"}\n"
"")
        self.popular_tv_shows_scroll_area.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.popular_tv_shows_scroll_area.setLineWidth(1)
        self.popular_tv_shows_scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.popular_tv_shows_scroll_area.setWidgetResizable(True)
        self.popular_tv_shows_scroll_area.setObjectName("popular_tv_shows_scroll_area")
        self.popular_tv_shows_scroll_area_contents = QtWidgets.QWidget()
        self.popular_tv_shows_scroll_area_contents.setGeometry(QtCore.QRect(0, 0, 830, 250))
        self.popular_tv_shows_scroll_area_contents.setObjectName("popular_tv_shows_scroll_area_contents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.popular_tv_shows_scroll_area_contents)
        self.gridLayout_2.setContentsMargins(-1, 9, -1, 9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.temp_tv_show_poster = QtWidgets.QLabel(parent=self.popular_tv_shows_scroll_area_contents)
        self.temp_tv_show_poster.setMinimumSize(QtCore.QSize(165, 225))
        self.temp_tv_show_poster.setMaximumSize(QtCore.QSize(165, 270))
        self.temp_tv_show_poster.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.temp_tv_show_poster.setStyleSheet("QLabel{\n"
"background-color: orange;\n"
"border-style: outset;\n"
"}\n"
"\n"
"QLabel:hover{\n"
"border: 4px solid blue;\n"
"border-radius: 1px;\n"
"}\n"
"\n"
"")
        self.temp_tv_show_poster.setText("")
        self.temp_tv_show_poster.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.temp_tv_show_poster.setObjectName("temp_tv_show_poster")
        self.gridLayout_2.addWidget(self.temp_tv_show_poster, 0, 0, 1, 1)
        self.popular_tv_shows_scroll_area.setWidget(self.popular_tv_shows_scroll_area_contents)
        self.gridLayout_4.addWidget(self.popular_tv_shows_scroll_area, 6, 1, 1, 1)
        self.popular_movie_week_frame = QtWidgets.QFrame(parent=self.choose_titles_page)
        self.popular_movie_week_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.popular_movie_week_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.popular_movie_week_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.popular_movie_week_frame.setObjectName("popular_movie_week_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.popular_movie_week_frame)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.popular_movie_week_label = QtWidgets.QLabel(parent=self.popular_movie_week_frame)
        self.popular_movie_week_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Oswald SemiBold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.popular_movie_week_label.setFont(font)
        self.popular_movie_week_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.popular_movie_week_label.setObjectName("popular_movie_week_label")
        self.horizontalLayout.addWidget(self.popular_movie_week_label)
        self.gridLayout_4.addWidget(self.popular_movie_week_frame, 3, 1, 1, 1)
        self.header_frame = QtWidgets.QFrame(parent=self.choose_titles_page)
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.header_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.search_movie_tv_show_label = QtWidgets.QLabel(parent=self.header_frame)
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(12)
        self.search_movie_tv_show_label.setFont(font)
        self.search_movie_tv_show_label.setObjectName("search_movie_tv_show_label")
        self.horizontalLayout_3.addWidget(self.search_movie_tv_show_label)
        self.search_title_line_edit = QtWidgets.QLineEdit(parent=self.header_frame)
        self.search_title_line_edit.setMinimumSize(QtCore.QSize(175, 25))
        self.search_title_line_edit.setMaximumSize(QtCore.QSize(175, 25))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(12)
        self.search_title_line_edit.setFont(font)
        self.search_title_line_edit.setText("")
        self.search_title_line_edit.setObjectName("search_title_line_edit")
        self.horizontalLayout_3.addWidget(self.search_title_line_edit)
        spacerItem2 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.frame = QtWidgets.QFrame(parent=self.header_frame)
        self.frame.setMinimumSize(QtCore.QSize(495, 50))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.liked_button = QtWidgets.QPushButton(parent=self.frame)
        self.liked_button.setMinimumSize(QtCore.QSize(60, 0))
        self.liked_button.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(12)
        self.liked_button.setFont(font)
        self.liked_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.liked_button.setStyleSheet("QPushButton{color: black; border: none; background-color: transparent;}\n"
"QPushButton:hover{color:green}")
        self.liked_button.setFlat(True)
        self.liked_button.setObjectName("liked_button")
        self.horizontalLayout_4.addWidget(self.liked_button)
        spacerItem4 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.to_watch_button = QtWidgets.QPushButton(parent=self.frame)
        self.to_watch_button.setMinimumSize(QtCore.QSize(60, 0))
        self.to_watch_button.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(12)
        self.to_watch_button.setFont(font)
        self.to_watch_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.to_watch_button.setStyleSheet("QPushButton{color: black; border: none; background-color: transparent;}\n"
"QPushButton:hover{color:green}")
        self.to_watch_button.setFlat(True)
        self.to_watch_button.setObjectName("to_watch_button")
        self.horizontalLayout_4.addWidget(self.to_watch_button)
        spacerItem5 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.reviewed_button = QtWidgets.QPushButton(parent=self.frame)
        self.reviewed_button.setMinimumSize(QtCore.QSize(60, 30))
        self.reviewed_button.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(12)
        self.reviewed_button.setFont(font)
        self.reviewed_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.reviewed_button.setStyleSheet("QPushButton{color: black; border: none; background-color: transparent;}\n"
"QPushButton:hover{color:green}")
        self.reviewed_button.setDefault(False)
        self.reviewed_button.setFlat(True)
        self.reviewed_button.setObjectName("reviewed_button")
        self.horizontalLayout_4.addWidget(self.reviewed_button)
        spacerItem6 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.members_button = QtWidgets.QPushButton(parent=self.frame)
        self.members_button.setMinimumSize(QtCore.QSize(60, 30))
        self.members_button.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(12)
        self.members_button.setFont(font)
        self.members_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.members_button.setStyleSheet("QPushButton{color: black; border: none; background-color: transparent;}\n"
"QPushButton:hover{color:green}")
        self.members_button.setFlat(True)
        self.members_button.setObjectName("members_button")
        self.horizontalLayout_4.addWidget(self.members_button)
        spacerItem7 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.logout_button = QtWidgets.QPushButton(parent=self.frame)
        self.logout_button.setMinimumSize(QtCore.QSize(60, 30))
        self.logout_button.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(12)
        self.logout_button.setFont(font)
        self.logout_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.logout_button.setStyleSheet("QPushButton{color: black; border: none; background-color: transparent;}\n"
"QPushButton:hover{color:green}")
        self.logout_button.setFlat(True)
        self.logout_button.setObjectName("logout_button")
        self.horizontalLayout_4.addWidget(self.logout_button)
        self.horizontalLayout_3.addWidget(self.frame)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.gridLayout_4.addWidget(self.header_frame, 1, 0, 1, 3)
        self.popular_tv_show_week_frame = QtWidgets.QFrame(parent=self.choose_titles_page)
        self.popular_tv_show_week_frame.setMaximumSize(QtCore.QSize(16777215, 75))
        self.popular_tv_show_week_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.popular_tv_show_week_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.popular_tv_show_week_frame.setObjectName("popular_tv_show_week_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.popular_tv_show_week_frame)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.popular_tv_show_week_label = QtWidgets.QLabel(parent=self.popular_tv_show_week_frame)
        self.popular_tv_show_week_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Oswald SemiBold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.popular_tv_show_week_label.setFont(font)
        self.popular_tv_show_week_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.popular_tv_show_week_label.setObjectName("popular_tv_show_week_label")
        self.horizontalLayout_2.addWidget(self.popular_tv_show_week_label)
        self.gridLayout_4.addWidget(self.popular_tv_show_week_frame, 5, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 3, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.gridLayout_4.addItem(spacerItem10, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.gridLayout_4.addItem(spacerItem11, 2, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 3, 2, 1, 1)
        self.stackedWidget.addWidget(self.choose_titles_page)
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.login_page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_3 = QtWidgets.QFrame(parent=self.login_page)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.no_account_label = QtWidgets.QLabel(parent=self.frame_3)
        self.no_account_label.setMinimumSize(QtCore.QSize(250, 30))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(12)
        self.no_account_label.setFont(font)
        self.no_account_label.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.no_account_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.no_account_label.setObjectName("no_account_label")
        self.gridLayout_7.addWidget(self.no_account_label, 3, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_7.addItem(spacerItem13, 0, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_7.addItem(spacerItem14, 0, 4, 1, 1)
        self.sign_up_button = QtWidgets.QPushButton(parent=self.frame_3)
        self.sign_up_button.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(12)
        self.sign_up_button.setFont(font)
        self.sign_up_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.sign_up_button.setStyleSheet("QPushButton:hover{\n"
"    color: blue;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: transparent;\n"
"}")
        self.sign_up_button.setFlat(True)
        self.sign_up_button.setObjectName("sign_up_button")
        self.gridLayout_7.addWidget(self.sign_up_button, 3, 2, 1, 1)
        self.filler_widget = QtWidgets.QWidget(parent=self.frame_3)
        self.filler_widget.setObjectName("filler_widget")
        self.gridLayout_7.addWidget(self.filler_widget, 3, 3, 1, 1)
        self.login_button = QtWidgets.QPushButton(parent=self.frame_3)
        self.login_button.setMinimumSize(QtCore.QSize(450, 75))
        self.login_button.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setFamily("Oswald Medium")
        font.setPointSize(16)
        self.login_button.setFont(font)
        self.login_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.login_button.setStyleSheet("")
        self.login_button.setObjectName("login_button")
        self.gridLayout_7.addWidget(self.login_button, 0, 1, 1, 3)
        self.gridLayout_5.addWidget(self.frame_3, 3, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(parent=self.login_page)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.password_label = QtWidgets.QLabel(parent=self.frame_2)
        self.password_label.setMaximumSize(QtCore.QSize(250, 40))
        font = QtGui.QFont()
        font.setFamily("Oswald Medium")
        font.setPointSize(18)
        self.password_label.setFont(font)
        self.password_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.password_label.setObjectName("password_label")
        self.gridLayout_6.addWidget(self.password_label, 2, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_6.addItem(spacerItem15, 0, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_6.addItem(spacerItem16, 6, 1, 1, 1)
        self.username_lineedit = QtWidgets.QLineEdit(parent=self.frame_2)
        self.username_lineedit.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(12)
        self.username_lineedit.setFont(font)
        self.username_lineedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.username_lineedit.setText("")
        self.username_lineedit.setObjectName("username_lineedit")
        self.gridLayout_6.addWidget(self.username_lineedit, 1, 1, 1, 1)
        self.password_lineedit = QtWidgets.QLineEdit(parent=self.frame_2)
        self.password_lineedit.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(12)
        self.password_lineedit.setFont(font)
        self.password_lineedit.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.password_lineedit.setText("")
        self.password_lineedit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_lineedit.setObjectName("password_lineedit")
        self.gridLayout_6.addWidget(self.password_lineedit, 2, 1, 1, 1)
        self.show_password_checkbox = QtWidgets.QCheckBox(parent=self.frame_2)
        self.show_password_checkbox.setEnabled(True)
        self.show_password_checkbox.setMinimumSize(QtCore.QSize(20, 25))
        self.show_password_checkbox.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(12)
        self.show_password_checkbox.setFont(font)
        self.show_password_checkbox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.show_password_checkbox.setCheckable(True)
        self.show_password_checkbox.setChecked(False)
        self.show_password_checkbox.setTristate(False)
        self.show_password_checkbox.setObjectName("show_password_checkbox")
        self.gridLayout_6.addWidget(self.show_password_checkbox, 5, 0, 1, 1)
        self.username_label = QtWidgets.QLabel(parent=self.frame_2)
        self.username_label.setMaximumSize(QtCore.QSize(250, 40))
        font = QtGui.QFont()
        font.setFamily("Oswald Medium")
        font.setPointSize(18)
        self.username_label.setFont(font)
        self.username_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.username_label.setObjectName("username_label")
        self.gridLayout_6.addWidget(self.username_label, 1, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_6.addItem(spacerItem17, 3, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_2, 2, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 125, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_5.addItem(spacerItem18, 0, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(0, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem19, 4, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem20, 2, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem21, 2, 2, 1, 1)
        self.title_label = QtWidgets.QLabel(parent=self.login_page)
        self.title_label.setMaximumSize(QtCore.QSize(16777215, 125))
        font = QtGui.QFont()
        font.setFamily("Oswald SemiBold")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.gridLayout_5.addWidget(self.title_label, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.login_page)
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.popular_movie_week_label.setText(_translate("MainWindow", "Popular movies for this week"))
        self.search_movie_tv_show_label.setText(_translate("MainWindow", "Search Movie/TV Show "))
        self.search_title_line_edit.setPlaceholderText(_translate("MainWindow", "Input name..."))
        self.liked_button.setText(_translate("MainWindow", "Liked"))
        self.to_watch_button.setText(_translate("MainWindow", "To Watch"))
        self.reviewed_button.setText(_translate("MainWindow", "Reviewed"))
        self.members_button.setText(_translate("MainWindow", "Members"))
        self.logout_button.setText(_translate("MainWindow", "Logout?"))
        self.popular_tv_show_week_label.setText(_translate("MainWindow", "Popular TV shows for this week"))
        self.no_account_label.setText(_translate("MainWindow", "Don\'t have an account?"))
        self.sign_up_button.setText(_translate("MainWindow", "Sign up"))
        self.login_button.setText(_translate("MainWindow", "Log In"))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.show_password_checkbox.setText(_translate("MainWindow", "Show password?"))
        self.username_label.setText(_translate("MainWindow", "Username"))
        self.title_label.setText(_translate("MainWindow", "Movie and TV Show Review App"))
